*** print_tb:  File "/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py", line 72, in giphy_tweet
    status = self.api.update_with_media('gif.GIF', status)
*** print_exception:Traceback (most recent call last):
  File "/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py", line 72, in giphy_tweet
    status = self.api.update_with_media('gif.GIF', status)
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 219, in update_with_media
    headers, post_data = API._pack_image(filename, 3072, form_field='media[]', f=f)
TweepError: File is too big, must be less than 3072kb.
*** print_exc:Traceback (most recent call last):
  File "/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py", line 72, in giphy_tweet
    status = self.api.update_with_media('gif.GIF', status)
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 219, in update_with_media
    headers, post_data = API._pack_image(filename, 3072, form_field='media[]', f=f)
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 1304, in _pack_image
    raise TweepError('File is too big, must be less than %skb.' % max_size)
TweepError: File is too big, must be less than 3072kb.
*** format_exc, first and last line:Traceback (most recent call last):TweepError: File is too big, must be less than 3072kb.*** format_exception:['Traceback (most recent call last):\n', '  File "/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py", line 72, in giphy_tweet\n    status = self.api.update_with_media(\'gif.GIF\', status)\n', '  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 219, in update_with_media\n    headers, post_data = API._pack_image(filename, 3072, form_field=\'media[]\', f=f)\n', '  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 1304, in _pack_image\n    raise TweepError(\'File is too big, must be less than %skb.\' % max_size)\n', 'TweepError: File is too big, must be less than 3072kb.\n']*** extract_tb:[('/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py', 72, 'giphy_tweet', "status = self.api.update_with_media('gif.GIF', status)"), ('/usr/local/lib/python2.7/site-packages/tweepy/api.py', 219, 'update_with_media', "headers, post_data = API._pack_image(filename, 3072, form_field='media[]', f=f)"), ('/usr/local/lib/python2.7/site-packages/tweepy/api.py', 1304, '_pack_image', "raise TweepError('File is too big, must be less than %skb.' % max_size)")]*** format_tb:['  File "/Users/mbp/Documents/projects/bots/heroku-twitterbot-starter-master/spaceb07/src/twitterAPI.py", line 72, in giphy_tweet\n    status = self.api.update_with_media(\'gif.GIF\', status)\n', '  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 219, in update_with_media\n    headers, post_data = API._pack_image(filename, 3072, form_field=\'media[]\', f=f)\n', '  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 1304, in _pack_image\n    raise TweepError(\'File is too big, must be less than %skb.\' % max_size)\n']*** tb_lineno:72